### PR TITLE
Config file

### PR DESCRIPTION
**Pull request by tallakahath**
Building in:
1. Software checking
2. SLURM support

See the full text of the last commit for details.

### CODE REVIEW

**Comment by tallakahath** [comment]
So... what is this still waiting on that I can do?

**Comment by julijavin** [comment]
I have been using this on NERSC and it has been working correctly.

**Comment by bpuchala** [comment]
I'm merging this into a new '2.X' development branch. Is there anything else ready that would be useful to include in a new release?

**Comment by tallakahath** [comment]
No, I made a 0.2.X branch (https://github.com/tallakahath/pbs/tree/0.2.X)
to consolidate all of *my* diffs into one place, but it appears my 0.2.X
and your 2.X are the same, so all is well (and you have all my latest,
hottest patches)

**Pull request closed without merging**
